[project]
name = "startup-orderbook-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinputplus>=0.2.12",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
    "ty>=0.0.1a32",
]
